version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - scalachallenge-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scalachallenge
      - POSTGRES_USER=scalachallenge
      - POSTGRES_PASSWORD=scalachallenge
  web:
    image: mozilla/sbt
    command: sbt shell
    working_dir: /app
    stdin_open: true
    tty: true
    #environment: &envVars
      #- AWS_DEFAULT_REGION=us-east-2
    volumes:
      - .:/app
      - ~/.ivy2:/root/.ivy2
      - ~/.sbt:/root/.sbt
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  scalachallenge-postgres-data:
