version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - scalachallenge-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scalachallenge
      - POSTGRES_USER=scalachallenge
      - POSTGRES_PASSWORD=scalachallenge
  web:
    image: scalachallenge:0.0.1-SNAPSHOT
    entrypoint: ["/opt/docker/bin/scalachallenge", "--", "${REVIEWS:-}"]
    volumes:
      - ./test-data:/opt/docker/test-data
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  scalachallenge-postgres-data:
